baseURL = "https://blog.geheimesite.nl/"
languageCode = "nl-nl"
title = "Webdevelopment-En-Meer"
paginate = 16
theme = "neofeed-theme"

[taxonomies]
tag = "tags"

[author]
name = "Robin Boers"
image = "https://geheimesite.nl/images/me.jpeg"
about = "Ik ben webdesigner, programmeur en nerd en ik woon in Maassluis. Ik ben 15 jaar oud en zit in de derde. Ik werk momenteel bij Qdentity."

[params]
skin = "macintosh"

# Totally optional cool stuff (see README for details)
#
# socialImage = "static/img/social.png" # site image for rich embeds
# customCSS = "css/style.css" # relative to ./static/
# plausible = true
# paymentPointer = "$wallet.provider.com/myspecialid123"
# webmentionUrl = "https://webmention.io/example/webmention"
# pingbackUrl = "https://webmention.io/example/xmlrpc"
# micropubUrl = "https://example.com/.netlify/functions/micropub"
# microsubUrl = "https://aperture.p3k.io/microsub/example"

# For IndieAuth and the author card
#
githubuser = "Robin Boers"

[permalinks]
feed = "/:title/"

[outputs]
  home = ["HTML", "JSON", "RSS"]
