baseURL = "https://blog.geheimesite.nl/en"
languageCode = "en-us"
title = "That Crazy Webdev"
paginate = 16
theme = "geheimesite"

[taxonomies]
tag = "tags"

[author]
name = "Robin Boers"
image = "https://geheimesite.nl/images/me.jpeg"
about = "I'm a webdesigner, programmer, and nerd living in the Netherlands. I'm 15 years old and I currently work at Qdentity."

[params]
skin = "macintosh"

# Totally optional cool stuff (see README for details)
#
# socialImage = "static/img/social.png" # site image for rich embeds
# customCSS = "css/style.css" # relative to ./static/
# plausible = true
# paymentPointer = "$wallet.provider.com/myspecialid123"
webmentionUrl = "https://webmention.io/geheimesite.nl/webmention"
pingbackUrl = "https://webmention.io/geheimesite.nl/xmlrpc"
# micropubUrl = "https://example.com/.netlify/functions/micropub"
# microsubUrl = "https://aperture.p3k.io/microsub/example"

# For IndieAuth and the author card
githubuser = "Robin Boers"
microblog = "Robijntje"

[permalinks]
feed = "/:title/"

[outputs]
  home = ["HTML", "JSON", "RSS"]
