name = "geheimesite"
license = "MIT"
licenselink = "https://github.com/RobinBoers/blob/master/theme/LICENSE"
description = "Simple neofeed-based theme for my blog."
homepage = "https://blog.geheimesite.nl"
tags = ["personal","timeline","feed","mobile","light","dark","dark mode","customizable","plausible"]
features = ["rss","json", "microformats2", "webmentions", "indieauth", "dark mode"]
min_version = "0.41"

[author]
  name = "Robin Boers"
  homepage = "https://geheimesite.nl"

[original]
  name = "Victoria Drake"
  homepage = "https://victoria.dev/neofeed-theme"
  repo = "https://github.com/victoriadrake/neofeed-theme"
