baseURL = "https://blog.geheimesite.nl/stupid-codes"
languageCode = "en-us"
title = "Stupid Codes"
paginate = 16
theme = "geheimesite"

[author]
name = "Robin Boers"
image = "https://geheimesite.nl/images/me.jpeg"
about = "I'm a webdesigner, programmer, and nerd living in the Netherlands. I'm 15 years old and I currently work at Qdentity."
githubuser = "RobinBoers"

[params]
webmentionUrl = "https://webmention.io/geheimesite.nl/webmention"
pingbackUrl = "https://webmention.io/geheimesite.nl/xmlrpc"
micropubUrl = "https://micro.geheimesite.nl/endpoint"
microsubUrl = "https://aperture.p3k.io/microsub/733"

[permalinks]
feed = "/:title/"

[outputs]
home = ["HTML", "JSON", "RSS"]

[taxonomies]
tag = "tags"