name: Send webmentions

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]

jobs:        
  send-nl:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    
    - name: Send webmentions (dutch blog)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: "https://blog.geheimesite.nl/index.json"
      run: |
        NEW=$(curl --silent $URL | jq -r first.uri)

        git diff --quiet $(git log -n 1 --pretty=format:"%p" master) master -- webdevelopment-en-meer/content || curl -X POST https://webmention.app/check?url="$NEW"
          
  send-en:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    
    - name: Send webmentions (english blog)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: "https://blog.geheimesite.nl/en/index.json"
      run: |
        NEW=$(curl --silent $URL | jq -r first.uri)
        git diff --quiet $(git log -n 1 --pretty=format:"%p" master) master -- crzywebdev/content || curl -X POST https://webmention.app/check?url="$NEW"