name: Send webmentions

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]

jobs:
  send-nl:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.commits[0].message, '#nl') }}
    steps:
    
    - name: Send webmentions (dutch blog)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: "https://blog.geheimesite.nl/index.json"
      run: |
        NEW=$(curl --silent $URL | jq -r first.uri)
        curl -X POST https://webmention.app/check?url="$NEW"
          
  send-en:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.commits[0].message, '#en') }}
    steps:
    
    - name: Send webmentions (english blog)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: "https://blog.geheimesite.nl/en/index.json"
      run: |
        NEW=$(curl --silent $URL | jq -r first.uri)
        curl -X POST https://webmention.app/check?url="$NEW"
